name: tmat-gis

services:
  vite-app:
    container_name: tmat-gis-app
    build:
      context: ..
      dockerfile: docker/Dockerfile
      args:
        VITE_BASE_PATH: ${VITE_BASE_PATH:-/}
    environment:
      APP_API_MODE: ${APP_API_MODE:-prod}
      APP_PROD_API_URL: ${APP_PROD_API_URL:-http://127.0.0.1:1880}
      APP_DEV_API_URL: ${APP_DEV_API_URL:-http://127.0.0.1:4000}
      APP_NAME: ${APP_NAME:-TMAT Monitor}
    ports:
      - "9001:80"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
